<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>db83808c-c336-4348-9757-ec232178a6ea</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Areas\Admin\Data\" />
    <Folder Include="Areas\Admin\Models\" />
    <Folder Include="Areas\Users\Data\" />
    <Folder Include="Areas\Users\Models\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Presentation\SingHub.WebAPI\SingHub.WebAPI.csproj" />
    <ProjectReference Include="..\SingHub.Dto\SingHub.Dto.csproj" />
  </ItemGroup>

</Project>
