<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>0caa10d7-a149-4c8d-bfbc-ba6ec251a75b</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.18" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.18">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Scalar.AspNetCore" Version="2.16.17" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Controllers\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Core\SingHub.Application\SingHub.Application.csproj" />
    <ProjectReference Include="..\..\Infrastructure\SingHub.Infrastructure\SingHub.Infrastructure.csproj" />
    <ProjectReference Include="..\..\Infrastructure\SingHub.Persistence\SingHub.Persistence.csproj" />
  </ItemGroup>

</Project>
